AstroFotoWebSite/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AstroFotoWebSite.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult AboutView()
        {
            return View();
        }
    }
}

AstroFotoWebSite/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AstroFotoWebSite.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult ContactView()
        {
            return View();
        }
    }
}

AstroFotoWebSite/Controllers/ObjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AstroFotoWebSite.Controllers
{
    public class ObjectController : Controller
    {
        // GET: Object
        [HttpGet]
        public ActionResult ObjectView()
        {
            return View();
        }
    }
}

AstroFotoWebSite/Controllers/UsefulController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AstroFotoWebSite.Controllers
{
    public class UsefulController : Controller
    {
        // GET: Useful
        public ActionResult UsefulView()
        {
            return View();
        }
    }
}

AstroFotoWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Добро пожаловать на мой сайт по астрофотографии!</title>
    @*<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src ="~/Scripts/bootstrap.min.js"></script>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Главная", "HomePage", "Home")</li>
                    <li>@Html.ActionLink("Галерея", "GalleryView", "Gallery")</li>
                    <li>@Html.ActionLink("Обьекты", "ObjectView", "Object")</li>
                    <li>@Html.ActionLink("Астропрогноз", "AstroForecastView", "AstroForecast")</li>
                    <li>@Html.ActionLink("Оборудование", "MySetupView", "MySetup")</li>
                    <li>@Html.ActionLink("Полезная информация", "UsefulView", "Useful")</li>
                    <li>@Html.ActionLink("Об авторе", "AboutView", "About")</li>
                    <li>@Html.ActionLink("Контакты", "ContactView", "Contact")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>        

   
            </div>
        </div>
    <div class="container body-content" style="background: #3B3B3B; margin-top: 20px">
        @RenderBody()
        <hr />
        <footer>
            <p style="color: White">&copy; @DateTime.Now.Year - Tkachenko Andrii. All rights reserved</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>